"""Initial setup with correct models

Revision ID: dfcd5e626909
Revises: 
Create Date: 2025-05-08 14:43:01.535290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcd5e626909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('orgao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('divisao_id', sa.Integer(), nullable=True),
    sa.Column('orgao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['divisao_id'], ['divisao.id'], ),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setor')
    op.drop_table('divisao')
    op.drop_table('orgao')
    # ### end Alembic commands ###
